name: dynamics
dependencies:
  - python=3.6
  - ipykernel
  - pytest
  - conda-forge::holoviews
  - conda-forge::altair
  - malramsay::sdanalysis=0.4.12
  - malramsay::sdrun=0.4.5
  - pip:
    - experi==0.2.2

