name: dynamics
channels:
  - default
  - conda-forge
  - glotzer
  - anaconda
dependencies:
  # Running simulations and data analysis
  - python=3.6
  - pip=19.1
  - pandas=0.25
  - bokeh=1.2
  - malramsay::sdanalysis=0.9.8
  - malramsay::sdrun=0.6.8
  - malramsay::experi=0.3.3
