name: dynamics
channels:
  - default
  - conda-forge
  - glotzer
  - anaconda
dependencies:
  # Running simulations and data analysis
  - python=3.6
  - pip=19.1
  - pandas=0.25
  - bokeh=1.2
  - malramsay::sdanalysis=0.11.2
  - malramsay::sdrun=0.6.8
  - malramsay::experi=0.3.3
  - pip:
    - "--editable .[dev]"
    - blacken-docs==1.3.0
  # Notebook/Interactive dependencies
  - altair=3.3
  - matplotlib=3.1
  - ipywidgets
  - nbdime=1.1
  - ipykernel=5.1.3
  - jupytext=1.2.4
  # Saving figures
  - selenium
  - geckodriver=0.24.0
  # Development dependencies
  - pytest=5.0
  - black=19.10b0
  - isort=4.3.21
  - hypothesis=4.23
  - mypy=0.740
  # Report Dependencies
  - pandoc
  - tectonic
  - cairosvg
  - pandocfilters==1.4.2
