name: dynamics
channels:
  - default
  - conda-forge
dependencies:
  # Running simulations and data analysis
  - python=3.6
  - pip
  - malramsay::sdanalysis=0.7.7
  - malramsay::sdrun=0.6.6
  - malramsay::experi=0.3.0
  # Notebook/Interactive dependencies
  - altair
  - matplotlib
  - seaborn
  - ipywidgets
  - nbdime
  - ipykernel
  - jupytext
  # Development dependencies
  - pytest
  - black
