name: dynamics
channels:
  - default
  - conda-forge
dependencies:
  # Running simulations and data analysis
  - python=3.6
  - pip
  - malramsay::sdanalysis=0.7.1
  - malramsay::sdrun=0.6.5
  - malramsay::experi=0.2.11
  # Notebook/Interactive dependencies
  - altair
  - matplotlib
  - seaborn
  - ipywidgets
  - nbdime
  - ipykernel
  # Development dependencies
  - pytest
