name: dynamics
dependencies:
  - python=3.6
  - ipykernel
  - pytest
  - glotzer::hoomd=2.2.5
  - conda-forge::holoviews
  - conda-forge::altair
  - malramsay::sdanalysis=0.5.5
  - malramsay::sdrun=0.6.0
  - malramsay::experi=0.2.6

