name: dynamics
channels:
  - default
  - conda-forge
dependencies:
  - python=3.6
  - ipykernel
  - pytest
  - altair
  - pip
  - matplotlib
  - nbdime
  - malramsay::sdanalysis=0.6.8
  - malramsay::sdrun=0.6.3
  - malramsay::experi=0.2.11
