name: dynamics
channels:
  - default
  - conda-forge
dependencies:
  # Running simulations and data analysis
  - python=3.6
  - pip
  - malramsay::sdanalysis=0.6.8
  - malramsay::sdrun=0.6.3
  - malramsay::experi=0.2.10
  # Notebook/Interactive dependencies
  - altair
  - matplotlib
  - ipywidgets
  - nbdime
  - ipykernel
  # Development dependencies
  - pytest
