name: Test source code

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Get conda info
        run: $CONDA/bin/conda info

      - name: Install environment using conda
        run: $CONDA/bin/conda env update --name dynamics

      - name: Activate conda environment
        run: source $CONDA/bin/activate dynamics

      - name: Run repository tests
        run: python3 -m pytest

      - name: Test analysis command
        run: dynamics_analysis --help

      - name: Test figures command
        run: dynamics_figures --help

      - name: Test experi command
        run: experi --help

      - name: Test jupytext command
        run: experi --help
