name: Test source code

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Get conda info
        run: $CONDA/bin/conda info

      - name: Install environment using conda
        run: $CONDA/bin/conda env update --name dynamics

      - name: Run repository tests
        run: source $CONDA/bin/activate dynamics && python3 -m pytest
