name: Test source code

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Install conda-forge channel
        run: $CONDA/bin/conda config --append channels conda-forge

      - name: Install glotzer channel
        run: $CONDA/bin/conda config --append channels glotzer

      - name: Install malramsay channel
        run: $CONDA/bin/conda config --append channels malramsay

      - name: Install mamba using conda
        run: $CONDA/bin/conda install mamba -y

        # Mamba has better error messages and progress reports
      - name: Install environment using mamba
        run: $CONDA/bin/mamba env update --name base

      - name: Run repository tests
        run: $CONDA/bin/pytest
