name: Test source code

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Install conda-forge channel
        run: $CONDA/bin/conda config --append channels conda-forge

      - name: Install glotzer channel
        run: $CONDA/bin/conda config --append channels glotzer

      - name: Install malramsay channel
        run: $CONDA/bin/conda config --append channels malramsay

      - name: Install python in environment
        run: $CONDA/bin/conda create --name dynamics python==3.6

      - name: Install environment using conda
        run: $CONDA/bin/conda env update --name dynamics

      - name: Run repository tests
        run: $CONDA/bin/envs/dynamics/bin/pytest
